name: Rust

on:
  push:
  pull_request:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: 'Log versions'
        run: |
          rustc --version
          cargo --version
      - name: Cache cargo
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-lint-${{ hashFiles('**/Cargo.lock') }}

      - name: Run clippy
        run: cargo clippy --verbose --all-targets --all-features -- -D warnings -D clippy::pedantic
      - name: Check format
        run: cargo fmt -- --check --verbose

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: 'Log versions'
        run: |
          rustc --version
          cargo --version
      - name: Cache cargo
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-test-${{ hashFiles('**/Cargo.lock') }}

      - name: Build
        run: cargo build --verbose --locked --all-targets

      - name: Run tests
        run: cargo test --verbose --all-targets

  release:
    name: Release ${{ matrix.config.triple }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      matrix:
        config:
          - os: ubuntu-latest
            triple: x86_64-unknown-linux-gnu
          - os: ubuntu-latest
            triple: armv7-unknown-linux-gnueabihf
          - os: ubuntu-latest
            triple: aarch64-unknown-linux-gnu
          - os: macOS-latest
            triple: x86_64-apple-darwin

    steps:
      - uses: actions/checkout@v2
      - name: Log versions
        run: |
          rustc --version
          cargo --version

      - name: install cross-compile armv7
        if: matrix.config.triple == 'armv7-unknown-linux-gnueabihf'
        run: |
          sudo apt-get install -y g++-arm-linux-gnueabihf
          mkdir -p ~/.cargo
          echo '[target.${{ matrix.config.triple }}]' > ~/.cargo/config
          echo 'linker = "arm-linux-gnueabihf-g++"' >> ~/.cargo/config

      - name: install cross-compile arm64
        if: matrix.config.triple == 'aarch64-unknown-linux-gnu'
        run: |
          sudo apt-get install -y g++-aarch64-linux-gnu
          mkdir -p ~/.cargo
          echo '[target.${{ matrix.config.triple }}]' > ~/.cargo/config
          echo 'linker = "aarch64-linux-gnu-g++"' >> ~/.cargo/config

      - name: Add Target
        run: rustup target add ${{ matrix.config.triple }}

      - name: Cache cargo
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ matrix.config.triple }}-cargo-release-${{ hashFiles('**/Cargo.lock') }}

      - name: Build release
        run: cargo build --release --verbose --locked --all-targets --target ${{ matrix.config.triple }}

      - name: inspect target dir
        if: runner.os == 'Linux' || runner.os == 'macOS'
        run: ls -al target/*/release

      - name: Upload Artifact (linux, mac)
        if: runner.os == 'Linux' || runner.os == 'macOS'
        uses: actions/upload-artifact@v2
        with:
          name: resilio-sync-watch-config-${{ matrix.config.triple }}
          path: target/${{ matrix.config.triple }}/release/resilio-sync-watch-config
      - name: Upload Artifact (windows)
        if: runner.os == 'Windows'
        uses: actions/upload-artifact@v2
        with:
          name: resilio-sync-watch-config-${{ matrix.config.triple }}
          path: target/${{ matrix.config.triple }}/release/resilio-sync-watch-config.exe

      - name: Pack release (linux, mac)
        if: runner.os == 'Linux' || runner.os == 'macOS'
        run: |
          rm -f *.tar.gz
          tar -czf resilio-sync-watch-config-${{ matrix.config.triple }}.tar.gz -C target/${{ matrix.config.triple }}/release resilio-sync-watch-config
      - name: Pack release (windows)
        if: runner.os == 'Windows'
        run: |
          del *.zip
          Compress-Archive -CompressionLevel Optimal -Force -Path target/${{ matrix.config.triple }}/release/resilio-sync-watch-config.exe -DestinationPath resilio-sync-watch-config-${{ matrix.config.triple }}.zip

      - name: GH Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          files: |
            *.zip
            *.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
